# Generated by Django 2.0 on 2018-09-18 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('working_schedule', models.CharField(max_length=150)),
                ('scheduled_pay', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=150)),
                ('work_address', models.TextField()),
                ('work_email', models.CharField(max_length=150)),
                ('work_phone', models.CharField(max_length=150)),
                ('public_info', models.TextField()),
                ('department', models.CharField(max_length=150)),
                ('job_title', models.CharField(max_length=150)),
                ('manager', models.CharField(max_length=150)),
                ('coach', models.CharField(max_length=150)),
                ('working_time', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='id_employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_of', to='employee_profile.Employee'),
        ),
    ]
